name: Win

on: [ "push", "pull_request", "workflow_dispatch" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: install diskspd
        run: |
          choco install -y diskspd
      
      - name: benchmark C
        run: |
          diskspd -c2G -w100 -b4K -F8 -r -o32 -W60 -d60 -Sh c:\testfile.dat
      
      - name: benchmark D
        run: |
          diskspd -c2G -w100 -b4K -F8 -r -o32 -W60 -d60 -Sh d:\testfile.dat
      
